### ISSUE TITLE
NodeJS integration

### ISSUE THREAD

**Issue by anhnt** [tvd12/ezyfox-server-example#17]
Firstly I'd like to thank you for your hard work on these projects. Looks great!

I have a use case where
- Admin can chat with multiple customers thru web UI (NodeJS server side and ReactJS client side)
- Customers can chat with admin via mobile apps (Flutter)
- Customers can chat to each other via mobile apps (Flutter)
- Push messages (Firebase Cloud Messaging) when someone receives a message but mobile apps are in background, and web notifications for admin when they receive messages as well

This has been done perfectly using Firebase, but I'd like to try ezyfox if that could adapt my needs. I can see nodejs example but this has only send message api. I'd like to have more APIs and webhook eg
- When someone receives a message

Please advise, thanks again!

**Comment by tvd12** [comment]
Thanks @anhnt , let me check it

**Comment by tvd12** [comment]
@anhnt can you take a look?
![ezyfox-server-chat-and-push](https://user-images.githubusercontent.com/6251901/126865819-96c6b837-0d53-4e42-839a-70b3aa241f83.png)

**Comment by tvd12** [comment]
@anhnt how to you think?

**Comment by anhnt** [comment]
@tvd12 Thanks so much for your hard work! Unfortunately I havent managed to check this due to my private issue
I hope to try it as soon as possible and get back
Many thanks again!

**Comment by brahimch217** [comment]
I think node Js is better then firebase because of the coast of firebase is more expansive then nodeJs so you do all of thus with a nodeJs back-end service

**Comment by tvd12** [comment]
@brahimch217 for push notification, we must use FCM
